default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "root" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEVELOPMENT") { "video_project_app_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") { "video_project_app_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRODUCTION") { "video_project_app_production" } %>
  username: <%= ENV["DB_USERNAME_PRODUCTION"] %>
  password: <%= ENV["DB_PASSWORD_PRODUCTION"] %>
